url: "https://voiceofthefathers.org" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  authors:
    output: true
    permalink: /authors/:name/
  books:
    output: true

markdown: kramdown

exclude:
  - README.md
  - TODO.md
  - AGENTS.md

safe: true
lsi: false
